#!/bin/bash

# Michael Neises
# 27 February 2023
# Collect, compose, and otherwise prepare my dissertation project for
# development and testing
# Modifications and improvements provided by OpenAI's ChatGPT-4

# Accept input as a command line argument
opt=$1

# Check if the argument was given
if [ -z "$opt" ]; then
    echo "No Linux kernel version provided. Note that 4.9.y is no longer supported."
    exit 1
fi

# Array of options
options=("4.9.y" "4.14.y" "4.19.y" "5.4.y" "5.10.y" "5.15.y" "6.1.y")

# Check if the argument is a valid option
valid=false
for i in "${options[@]}"; do
    if [ "$i" == "$opt" ]; then
        valid=true
        break
    fi
done

if $valid; then
    echo "You chose version $opt"
else
    echo "Invalid option $opt"
    exit 1
fi


# 1. Create a directory named for the version of linux
dir="/mnt/continteg/dev/$opt-linux"

# Navigate into the created directory
cd "${dir}" || { echo "Failed to change directory to: ${dir}"; exit 1; }

# 4. Place an update script in today's directory
# Creates a script to update the project
cat <<EOF > updateProject.sh
# Step 1: Remove contents of test_build/attarch except the linux subdirectory
find test_bench/attarch/ -mindepth 1 -type d -not -wholename '*/linux-stable/*' -not -name 'linux-stable' -not -path '*/IntrospectionLibrary.c' -not -path '*/linux_definitions.h' -exec rm -rf {} +
rsync -av attarch/ test_bench/attarch/ &&
rsync -av am-cakeml/ test_bench/attarch/am-cakeml/
EOF

# 5. Create a test_bench directory and check if operation was successful
cd test_bench || { echo "Failed to change directory to: test_bench"; exit 1; }

# 8. edit the extras.Dockerfile to get the right version of cakeML
# Append Dockerfile with commands to fetch the right version of CakeML
cat <<EOF >> seL4-CAmkES-L4v-dockerfiles/dockerfiles/extras.Dockerfile
RUN curl -L https://github.com/CakeML/cakeml/releases/download/v2076/cake-x64-32.tar.gz > cake-x64-32.tar.gz \\
    && tar -xvzf cake-x64-32.tar.gz && cd cake-x64-32 && make cake \\
    && mv cake /usr/bin/cake32

RUN curl -L https://github.com/CakeML/cakeml/releases/download/v2076/cake-x64-64.tar.gz > cake-x64-64.tar.gz \\
    && tar -xvzf cake-x64-64.tar.gz && cd cake-x64-64 && make cake \
&& mv cake /usr/bin/cake64
EOF

# 11. Collect necessary definitions from the System.map file generated by
# building the linux kernel last step
cd attarch
python3 ScrapeSystemMap.py > components/Measurement/configurations/linux_definitions.h || { echo "Failed to run ScrapeSystemMap.py"; exit 1; }

# 12. Amend the top level IntrospectionLibrary.c file to include the right
# library for the chosen version of linux
cat <<EOF >> components/Measurement/IntrospectionLibrary/IntrospectionLibrary.c
#include "${opt}/library.c"
EOF


echo "done"

# from GPT:
# In this version, I added error checks after directory and repository operations, quoted all variables, and used heredocs (`<<EOF`) to make the inline script and Dockerfile additions more readable. I also made clear where each error check and modification was made.










