#!/bin/bash

# Michael Neises
# 27 February 2023
# Collect, compose, and otherwise prepare my dissertation project for
# development and testing
# Modifications and improvements provided by OpenAI's ChatGPT-4

# Accept input as a command line argument
opt=$1

# Check if the argument was given
if [ -z "$opt" ]; then
    echo "No Linux kernel version provided. Note that 4.9.y is no longer supported."
    exit 1
fi

# Array of options
options=("4.9.y" "4.14.y" "4.19.y" "5.4.y" "5.10.y" "5.15.y" "6.1.y")

# Check if the argument is a valid option
valid=false
for i in "${options[@]}"; do
    if [ "$i" == "$opt" ]; then
        valid=true
        break
    fi
done

if $valid; then
    echo "You chose version $opt"
else
    echo "Invalid option $opt"
    exit 1
fi


# 1. Create a directory named for the version of linux
dir="$opt-linux"
cd "${dir}/test_bench/attarch" || { echo "Failed to change directory to: ${dir}/test_bench/attarch"; exit 1; }

# 11. Collect necessary definitions from the System.map file generated by
# building the linux kernel last step
python3 ScrapeSystemMap.py >> components/Measurement/configurations/linux_definitions.h || { echo "Failed to run ScrapeSystemMap.py"; exit 1; }

# 12. Amend the top level IntrospectionLibrary.c file to include the right
# library for the chosen version of linux
cat <<EOF >> components/Measurement/IntrospectionLibrary/IntrospectionLibrary.c
#include "${opt}/library.c"
EOF

echo "done"
